[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
 默认运行参数（无需每次命令行输入）
addopts = -vs
        --alluredir=./reports/allure-results
         --clean-alluredir
          --reruns=0
          --reruns-delay=3


# 忽略警告（可选）
filterwarnings = ignore::DeprecationWarning


markers =
    smoke: 冒烟测试用例
    regress: 回归测试用例